=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::ApproverEmailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApproverEmailApi' do
  before do
    # run before each test
    @instance = OpenProvider::ApproverEmailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApproverEmailApi' do
    it 'should create an instance of ApproverEmailApi' do
      expect(@instance).to be_instance_of(OpenProvider::ApproverEmailApi)
    end
  end

  # unit tests for list_approver_emails
  # List approver emails
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :product_id ID of product order will be created for.
  # @option opts [String] :domain Domain name.
  # @return [ApproveremailListApproverEmailsResponse]
  describe 'list_approver_emails test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
