=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::ContactServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactServiceApi' do
  before do
    # run before each test
    @instance = OpenProvider::ContactServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactServiceApi' do
    it 'should create an instance of ContactServiceApi' do
      expect(@instance).to be_instance_of(OpenProvider::ContactServiceApi)
    end
  end

  # unit tests for create_contact
  # Create contact
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ContactCreateContactResponse]
  describe 'create_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_contact
  # Delete contact
  # @param id Object ID
  # @param [Hash] opts the optional parameters
  # @return [ContactDeleteContactResponse]
  describe 'delete_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_contact
  # Get contact
  # @param id Object ID
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :with_additional_data Retrieves objects with (1) or without (0) additional data.
  # @return [ContactGetContactResponse]
  describe 'get_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_contacts
  # List contacts
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Output limit.
  # @option opts [Integer] :offset Output offset.
  # @option opts [String] :order Output ordering pattern. ASC / DESC.
  # @option opts [String] :order_by Order output by field (i.e. first_name).
  # @option opts [String] :email_pattern Full or partial email address. Wildcard (*) can be used.
  # @option opts [String] :last_name_pattern Full or partial last name. Wildcard (*) can be used.
  # @option opts [String] :company_name_pattern Full or partial company name. Wildcard (*) can be used.
  # @option opts [String] :username_pattern The username pattern.
  # @option opts [String] :role Contact&#x27;s role.
  # @option opts [BOOLEAN] :with_additional_data Retrieves objects with (1) or without (0) additional data.
  # @return [ContactListContactsResponse]
  describe 'list_contacts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_contact
  # Update contact
  # @param body 
  # @param id Object ID
  # @param [Hash] opts the optional parameters
  # @return [ContactUpdateContactResponse]
  describe 'update_contact test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
