=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::CustomerAdditionalDataApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerAdditionalDataApi' do
  before do
    # run before each test
    @instance = OpenProvider::CustomerAdditionalDataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerAdditionalDataApi' do
    it 'should create an instance of CustomerAdditionalDataApi' do
      expect(@instance).to be_instance_of(OpenProvider::CustomerAdditionalDataApi)
    end
  end

  # unit tests for get_data
  # Get data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain_name Domain name without extension.
  # @option opts [String] :domain_extension Domain extension.
  # @return [CustomerGetDataResponse]
  describe 'get_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
