=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::EmailVerificationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmailVerificationApi' do
  before do
    # run before each test
    @instance = OpenProvider::EmailVerificationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailVerificationApi' do
    it 'should create an instance of EmailVerificationApi' do
      expect(@instance).to be_instance_of(OpenProvider::EmailVerificationApi)
    end
  end

  # unit tests for list_domain_email_verifications
  # List domain email verifications
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :domain_id The domain id.
  # @option opts [String] :domain The domain.
  # @option opts [String] :email The email.
  # @option opts [String] :handle The handle.
  # @option opts [String] :status The status.
  # @option opts [String] :description The description.
  # @option opts [BOOLEAN] :is_suspended Is suspended.
  # @option opts [String] :response_type The type.
  # @option opts [String] :response_to The to.
  # @option opts [Integer] :limit The limit.
  # @option opts [Integer] :offset The offset.
  # @return [EmailListDomainVerificationsResponse]
  describe 'list_domain_email_verifications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for restart_email_verification
  # Restart email verification
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [EmailRestartEmailVerificationResponse]
  describe 'restart_email_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for start_email_verification
  # Start email verification
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [EmailStartEmailVerificationResponse]
  describe 'start_email_verification test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
