=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::EmailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmailApi' do
  before do
    # run before each test
    @instance = OpenProvider::EmailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailApi' do
    it 'should create an instance of EmailApi' do
      expect(@instance).to be_instance_of(OpenProvider::EmailApi)
    end
  end

  # unit tests for create_email
  # Create email
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [EmailCreateEmailResponse]
  describe 'create_email test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_email
  # Delete email
  # @param id Object ID
  # @param [Hash] opts the optional parameters
  # @return [EmailDeleteEmailResponse]
  describe 'delete_email test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_emails
  # List emails
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :id Object ID.
  # @option opts [String] :name Template name.
  # @option opts [String] :group Email template type. There are several types of ICANN emails that can be customized in Openprovider: -errp (Expired Registration Recovery policy emails) -foa (Form of Authorization emails for domain transfers approval rejection) -ive (Information verification emails, such emails used to verify email address of the customer) -tcn (Trademark Claims Notification emails) -wdrp (Whois Data Reminder Policy emails).
  # @option opts [Integer] :limit Output limit.
  # @option opts [Integer] :offset Output offset.
  # @option opts [BOOLEAN] :is_system Is system.
  # @return [EmailListEmailsResponse]
  describe 'list_emails test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_email
  # Update email
  # @param body 
  # @param id Object ID
  # @param [Hash] opts the optional parameters
  # @return [EmailUpdateEmailResponse]
  describe 'update_email test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
