=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::OtpTokenApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OtpTokenApi' do
  before do
    # run before each test
    @instance = OpenProvider::OtpTokenApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OtpTokenApi' do
    it 'should create an instance of OtpTokenApi' do
      expect(@instance).to be_instance_of(OpenProvider::OtpTokenApi)
    end
  end

  # unit tests for create_otp_token
  # Create otp token
  # @param body 
  # @param id Object id
  # @param [Hash] opts the optional parameters
  # @return [OtptokenCreateOtpTokenResponse]
  describe 'create_otp_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
