=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::ResellerServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResellerServiceApi' do
  before do
    # run before each test
    @instance = OpenProvider::ResellerServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResellerServiceApi' do
    it 'should create an instance of ResellerServiceApi' do
      expect(@instance).to be_instance_of(OpenProvider::ResellerServiceApi)
    end
  end

  # unit tests for get_reseller
  # Get reseller
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :with_additional_data Retrieves objects with (1) or without (0) additional data.
  # @option opts [BOOLEAN] :with_statistics Indicates if reseller statistics should be retrieved.
  # @option opts [BOOLEAN] :with_settings Indicates if reseller settings should be retrieved.
  # @option opts [BOOLEAN] :with_contacts Indicates if reseller contacts should be retrieved.
  # @return [ResellerGetResellerResponse]
  describe 'get_reseller test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_reseller
  # Update reseller
  # @param body 
  # @param id Object ID
  # @param [Hash] opts the optional parameters
  # @return [ResellerUpdateResellerResponse]
  describe 'update_reseller test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
