=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::TldServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TldServiceApi' do
  before do
    # run before each test
    @instance = OpenProvider::TldServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TldServiceApi' do
    it 'should create an instance of TldServiceApi' do
      expect(@instance).to be_instance_of(OpenProvider::TldServiceApi)
    end
  end

  # unit tests for get_tld
  # Get tld
  # @param name Extension name
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Search query limit.
  # @option opts [Integer] :offset Search query offset.
  # @option opts [BOOLEAN] :with_description Returns additional extension description.
  # @option opts [BOOLEAN] :with_restrictions Returns list of extension restrictions.
  # @option opts [BOOLEAN] :with_price Returns extension prices.
  # @option opts [BOOLEAN] :with_level_prices Returns extension prices for each Openprovider discount tier.
  # @option opts [BOOLEAN] :with_usage_count Returns number of domains using specified extension in this account.
  # @option opts [Array<String>] :status Extension status.
  # @return [TldGetTldResponse]
  describe 'get_tld test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_tlds
  # List tlds
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Search query limit.
  # @option opts [Integer] :offset Search query offset.
  # @option opts [String] :order Sorts output ASC or DESC.
  # @option opts [String] :order_by Sorts output by a field.
  # @option opts [Array<String>] :extensions Array of extensions.
  # @option opts [String] :name_pattern Extension name pattern. Wildcard (*) can be used.
  # @option opts [BOOLEAN] :only_names Returns only extension names in the output.
  # @option opts [BOOLEAN] :with_description Returns additional extension description.
  # @option opts [BOOLEAN] :with_restrictions Returns list of extension restrictions.
  # @option opts [BOOLEAN] :with_usage_count Returns number of domains using specified extension in this account.
  # @option opts [Array<String>] :with_application_mode Array of extension application modes.
  # @option opts [BOOLEAN] :with_price Returns extension prices.
  # @option opts [BOOLEAN] :with_level_prices Returns extension prices for each Openprovider discount tier.
  # @option opts [BOOLEAN] :is_active Indicates, if extension is active.
  # @option opts [BOOLEAN] :is_new_gtld Indicates, if extension is a newGTLD.
  # @option opts [String] :status Extension status.
  # @option opts [String] :application_mode Pre-registration mode.
  # @return [TldListTldsResponse]
  describe 'list_tlds test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
