=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'spec_helper'
require 'json'

# Unit tests for OpenProvider::ZoneRecordServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ZoneRecordServiceApi' do
  before do
    # run before each test
    @instance = OpenProvider::ZoneRecordServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ZoneRecordServiceApi' do
    it 'should create an instance of ZoneRecordServiceApi' do
      expect(@instance).to be_instance_of(OpenProvider::ZoneRecordServiceApi)
    end
  end

  # unit tests for list_zone_records
  # List zone records
  # @param name DNS record name
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :zone_id DNS zone ID.
  # @option opts [Integer] :limit How many records to retrieve (default: 100, max 500).
  # @option opts [Integer] :offset From which record to retrieve (default: 0).
  # @option opts [String] :order_by_type Sorting type (asc/desc).
  # @option opts [String] :order_by_name Sorting type (asc/desc).
  # @option opts [String] :order_by_value Sorting type (asc/desc).
  # @option opts [String] :order_by_ttl Sorting type (asc/desc).
  # @option opts [String] :order_by_prio Sorting type (asc/desc).
  # @option opts [String] :record_name_pattern DNS record name pattern. Wildcard (*) can be used.
  # @option opts [String] :value_pattern DNS record value pattern. Wildcard (*) can be used.
  # @option opts [String] :type DNS record type.
  # @option opts [Integer] :prio DNS record priority.
  # @option opts [Integer] :ttl DNS record TTL.
  # @option opts [String] :zone_provider Name of the DNS provider. Set zone_provider&#x3D;sectigo in case of only sectigo premium DNS zone records should be retrieved.
  # @return [RecordListZoneRecordsResponse]
  describe 'list_zone_records test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
