=begin
#REST API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.30
=end

require 'date'

module OpenProvider
  class TldPrices
    attr_accessor :create_price

    attr_accessor :domicile_price

    attr_accessor :max_period

    attr_accessor :min_period

    attr_accessor :renew_price

    attr_accessor :reseller_price

    attr_accessor :restore_price

    attr_accessor :setup_price

    attr_accessor :soft_restore_price

    attr_accessor :trade_price

    attr_accessor :transfer_price

    attr_accessor :update_price

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'create_price' => :'create_price',
        :'domicile_price' => :'domicile_price',
        :'max_period' => :'max_period',
        :'min_period' => :'min_period',
        :'renew_price' => :'renew_price',
        :'reseller_price' => :'reseller_price',
        :'restore_price' => :'restore_price',
        :'setup_price' => :'setup_price',
        :'soft_restore_price' => :'soft_restore_price',
        :'trade_price' => :'trade_price',
        :'transfer_price' => :'transfer_price',
        :'update_price' => :'update_price'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'create_price' => :'Object',
        :'domicile_price' => :'Object',
        :'max_period' => :'Object',
        :'min_period' => :'Object',
        :'renew_price' => :'Object',
        :'reseller_price' => :'Object',
        :'restore_price' => :'Object',
        :'setup_price' => :'Object',
        :'soft_restore_price' => :'Object',
        :'trade_price' => :'Object',
        :'transfer_price' => :'Object',
        :'update_price' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenProvider::TldPrices` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenProvider::TldPrices`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'create_price')
        self.create_price = attributes[:'create_price']
      end

      if attributes.key?(:'domicile_price')
        self.domicile_price = attributes[:'domicile_price']
      end

      if attributes.key?(:'max_period')
        self.max_period = attributes[:'max_period']
      end

      if attributes.key?(:'min_period')
        self.min_period = attributes[:'min_period']
      end

      if attributes.key?(:'renew_price')
        self.renew_price = attributes[:'renew_price']
      end

      if attributes.key?(:'reseller_price')
        self.reseller_price = attributes[:'reseller_price']
      end

      if attributes.key?(:'restore_price')
        self.restore_price = attributes[:'restore_price']
      end

      if attributes.key?(:'setup_price')
        self.setup_price = attributes[:'setup_price']
      end

      if attributes.key?(:'soft_restore_price')
        self.soft_restore_price = attributes[:'soft_restore_price']
      end

      if attributes.key?(:'trade_price')
        self.trade_price = attributes[:'trade_price']
      end

      if attributes.key?(:'transfer_price')
        self.transfer_price = attributes[:'transfer_price']
      end

      if attributes.key?(:'update_price')
        self.update_price = attributes[:'update_price']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          create_price == o.create_price &&
          domicile_price == o.domicile_price &&
          max_period == o.max_period &&
          min_period == o.min_period &&
          renew_price == o.renew_price &&
          reseller_price == o.reseller_price &&
          restore_price == o.restore_price &&
          setup_price == o.setup_price &&
          soft_restore_price == o.soft_restore_price &&
          trade_price == o.trade_price &&
          transfer_price == o.transfer_price &&
          update_price == o.update_price
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [create_price, domicile_price, max_period, min_period, renew_price, reseller_price, restore_price, setup_price, soft_restore_price, trade_price, transfer_price, update_price].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        OpenProvider.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
